---
- name: Get ARP information
  hosts: all
  gather_facts: false


  tasks:
    - name: show ip arp
      raw: "show ip arp"

      register: print_output

    -  debug: var=print_output.stdout_lines
